site_name: Redis-ML - Machine Learning Model Server on Redis
site_url: https://redisml.io
repo_url: https://github.com/RedisLabsModules/redis-ml
repo_name: RedisLabsModules/redis-ml
theme: material

extra:
  palette:
    primary: 'indigo'
  logo: 'images/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/redislabs'
    - type: 'twitter'
      link: 'https://twitter.com/redislabs'

pages:
    - 'Quickstart': 'index.md'
    - 'Commands': 'commands.md'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)